/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basededatos2;

import static basededatos2.elim_usuario.cn;
import ds.desktop.notify.DesktopNotify;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author hance
 */
public class mvalidacion extends javax.swing.JFrame {
static Connection cn;
 static Statement s;
 static ResultSet rs;
 
 String nb=Pantallap.usuariodb;
 String cont=Pantallap.cnusuariobd;
    /**
     * Creates new form validacion
     */
    public mvalidacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargar_imagen1();
        comnom();
        comnom1();
        mas1.setVisible(false);
        cnombre1.setVisible(false);
    }
 public void cargar_imagen1 (){
       ImageIcon imagen = new ImageIcon ("C://Users//hance//Documents//IMAGENES PROYECTOS//fondo1.jpg");
        Icon icono = new ImageIcon (imagen.getImage().getScaledInstance(fondo.getWidth(), fondo.getHeight(), Image.SCALE_DEFAULT));
        fondo.setIcon(icono);
        this.repaint();
       }
 public void comnom()
    {
        try{
            cn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE",nb,cont);
            s=cn.createStatement();
            rs=s.executeQuery("select nombre from control_sistema where estado='activo'");
            cnombre.removeAllItems();
            while(rs.next()){
            cnombre.addItem(rs.getString(1));
            }
            cn.close();
        }
        catch(Exception ex)
        {
            System.out.println(ex.getMessage());
            
        }
    }
 public void comnom1()
    {
        try{
            cn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE",nb,cont);
            s=cn.createStatement();
            rs=s.executeQuery("select nombre from control_sistema where estado ='inactivo'");
            cnombre1.removeAllItems();
            while(rs.next()){
            cnombre1.addItem(rs.getString(1));
            }
            cn.close();
        }
        catch(Exception ex)
        {
            System.out.println(ex.getMessage());
            
        }
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmonto = new javax.swing.JLabel();
        tmonto = new javax.swing.JTextField();
        mas = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cnombre = new javax.swing.JComboBox<>();
        alta = new javax.swing.JCheckBox();
        cnombre1 = new javax.swing.JComboBox<>();
        mas1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jmonto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmonto.setForeground(new java.awt.Color(102, 204, 0));
        jmonto.setText("MONTO");
        getContentPane().add(jmonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 64, 34));
        getContentPane().add(tmonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 140, 30));

        mas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar.png"))); // NOI18N
        mas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masMouseClicked(evt);
            }
        });
        getContentPane().add(mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 70, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar_cancelar.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 70, 70));

        cnombre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cnombre.setForeground(new java.awt.Color(102, 204, 0));
        cnombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre" }));
        cnombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cnombreMouseClicked(evt);
            }
        });
        getContentPane().add(cnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 220, -1));

        alta.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        alta.setForeground(new java.awt.Color(102, 204, 0));
        alta.setText("DAR DE ALTA");
        alta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                altaMouseClicked(evt);
            }
        });
        getContentPane().add(alta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        cnombre1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cnombre1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre" }));
        getContentPane().add(cnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 230, -1));

        mas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar.png"))); // NOI18N
        mas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mas1MouseClicked(evt);
            }
        });
        getContentPane().add(mas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, 70));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 593, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void masMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masMouseClicked

        try {
            String n = cnombre.getSelectedItem().toString();
            int mo= Integer.parseInt(tmonto.getText());
            elus(n,mo);
            this.dispose();
        } catch (Exception e) {
             DesktopNotify.showDesktopMessage("Mensaje de Fallo", "No se permiten Caracteres en el campo de Monto "+e.getMessage()+".", DesktopNotify.FAIL);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_masMouseClicked

    private void cnombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnombreMouseClicked
    comnom();        // TODO add your handling code here:
    }//GEN-LAST:event_cnombreMouseClicked

    private void altaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_altaMouseClicked
if(alta.isSelected()){
cnombre.setEnabled(false);
tmonto.setVisible(false);
jmonto.setVisible(false);
mas.setVisible(false);
mas1.setVisible(true);
cnombre1.setVisible(true);
}else{
cnombre.setEnabled(true);
tmonto.setVisible(true);
jmonto.setVisible(true);
mas.setVisible(true);
mas1.setVisible(false);
cnombre1.setVisible(false);
}        // TODO add your handling code here:
    }//GEN-LAST:event_altaMouseClicked

    private void mas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mas1MouseClicked

        altus(cnombre1.getSelectedItem().toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_mas1MouseClicked
 public void elus(String nom,int mont ){
        try{

            cn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE",nb,cont);
            s=cn.createStatement();
            rs=s.executeQuery("begin "
                             + "modificar_control ('"+nom+"',"+mont+");"
                             + "end;");
             DesktopNotify.showDesktopMessage("Mensaje de Éxito", "Usuario "+nom+" ha sido modificado.", DesktopNotify.SUCCESS);
          cn.close();
          s.close();
          rs.close();
          
        }
        catch(Exception ex)
        {
            DesktopNotify.showDesktopMessage("Mensaje de Fallo", "No se pudo crear la Nueva validacion."+ex.getMessage()+".", DesktopNotify.FAIL);
                     }
    }
  public void altus(String nom ){
        try{

            cn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE",nb,cont);
            s=cn.createStatement();
            rs=s.executeQuery("begin "
                             + "dardealta_controlsistema ('"+nom+"');"
                             + "end;");
             DesktopNotify.showDesktopMessage("Mensaje de Éxito", "Usuario "+nom+" ha sido dado de alta.", DesktopNotify.SUCCESS);
          cn.close();
          s.close();
          rs.close();
          
        }
        catch(Exception ex)
        {
            DesktopNotify.showDesktopMessage("Mensaje de Fallo", "No se pudo crear la Nueva validacion."+ex.getMessage()+".", DesktopNotify.FAIL);
                     }
    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mvalidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mvalidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mvalidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mvalidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mvalidacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox alta;
    private javax.swing.JComboBox<String> cnombre;
    private javax.swing.JComboBox<String> cnombre1;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jmonto;
    private javax.swing.JLabel mas;
    private javax.swing.JLabel mas1;
    private javax.swing.JTextField tmonto;
    // End of variables declaration//GEN-END:variables
}
