/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basededatos2;

import static basededatos2.P_administrador.cn;
import ds.desktop.notify.DesktopNotify;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author hance
 */
public class Nuevo_banco extends javax.swing.JFrame {
static Connection cn;
 static Statement s;
 static ResultSet rs;
 
 String usuario=Pantallap.usuariodb;;
 String cnt=Pantallap.cnusuariobd;
    /**
     * Creates new form Nuevo_banco
     */
    public Nuevo_banco() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        cargar_imagen();
    }
    public void cargar_imagen (){
       ImageIcon imagen = new ImageIcon ("C://Users//hance//Documents//IMAGENES PROYECTOS//bank.jpg");
        Icon icono = new ImageIcon (imagen.getImage().getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_DEFAULT));
        logo.setIcon(icono);
        this.repaint();
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jusuario = new javax.swing.JTextField();
        jcantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jusuario.setText("Nombre del banco");
        jusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jusuarioMouseClicked(evt);
            }
        });
        getContentPane().add(jusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 220, 40));

        jcantidad.setText("Monto Inicial");
        jcantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcantidadMouseClicked(evt);
            }
        });
        getContentPane().add(jcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 220, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar.png"))); // NOI18N
        jLabel2.setText(" ");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 70, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar_cancelar.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 290, 70, 70));
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 600, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jusuarioMouseClicked
jusuario.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jusuarioMouseClicked

    private void jcantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcantidadMouseClicked
jcantidad.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jcantidadMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        
String nm =jusuario.getText();
int j= Integer.parseInt(jcantidad.getText());
nuevo_banco(nm, j);


        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    public void nuevo_banco(String nom,int mont)
    {
        try{
            cn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE",usuario,cnt);
            s=cn.createStatement();
            rs=s.executeQuery("begin "
                            + "crear_cbanco('"+nom+"',"+mont+");"
                            + " end;");
            
            cn.close();
            DesktopNotify.showDesktopMessage("Mensaje de Éxito", "Banco: "+nom+" Creado Correctamente con un Saldo inicial de:"+ mont +" ", DesktopNotify.SUCCESS);
            this.dispose();
        }
        catch(Exception ex)
        {
            System.out.println(ex.getMessage());
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuevo_banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuevo_banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuevo_banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuevo_banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nuevo_banco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jcantidad;
    private javax.swing.JTextField jusuario;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
