/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basededatos2;

import static basededatos2.P_administrador.cnn;
import static basededatos2.elim_usuario.cn;
import ds.desktop.notify.DesktopNotify;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hance
 */
public class UsuarioFinal extends javax.swing.JFrame {
static Connection cn;
 static Statement s;
 static ResultSet rs;
 
 String nb="ADMINISTRADOR";
 String cont="12345";
    /**
     * Creates new form validacion
     */
    public UsuarioFinal() {
        initComponents();
        cargar_imagen1();
        vercheque();
        combo();
    }
 public void cargar_imagen1 (){
       ImageIcon imagen = new ImageIcon ("C://Users//hance//Documents//IMAGENES PROYECTOS//fondo1.jpg");
        Icon icono = new ImageIcon (imagen.getImage().getScaledInstance(fondo.getWidth(), fondo.getHeight(), Image.SCALE_DEFAULT));
        fondo.setIcon(icono);
        this.repaint();
       }
 public void combo()
    {
        try{
            cn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE",nb,cont);
            s=cn.createStatement();
            rs=s.executeQuery(" select id_cheque from cheques where estado ='disponible'");
            ccheque.removeAllItems();
            while(rs.next()){
            ccheque.addItem(rs.getString(1));
            }
            cn.close();
        }
        catch(Exception ex)
        {
            System.out.println(ex.getMessage());
            
        }
    }
 public void vercheque (){
try {   
     DefaultTableModel modelo2 = new DefaultTableModel();
      int cantidadc;
            modelo2.setRowCount(0);
            String url = "jdbc:oracle:thin:@localhost:1521:XE";
           
            cnn = DriverManager.getConnection(url, nb,cont);
            //Para ejecutar la consulta
            s = cnn.createStatement();
            //Ejecutamos la consulta y los datos lo almacenamos en un ResultSet
                 
            rs = s.executeQuery("select * from cheques where estado ='disponible' ");
            //Obteniendo la informacion de las columnas que estan siendo consultadas
            ResultSetMetaData rsd = rs.getMetaData();
            
            cantidadc = rsd.getColumnCount();
            for (int i = 1; i <= cantidadc; i++) {
             modelo2.addColumn(rsd.getColumnLabel(i));
            }
            Object[] fila = new Object[cantidadc];
            //Creando las filas para el JTable
            while (rs.next()) {
             
             for (int i = 0; i < cantidadc; i++) {
               fila[i]=rs.getObject(i+1);
             }
             modelo2.addRow(fila);
            }
            tcheque.setModel(modelo2);
            cnn.close();
            
       } catch (Exception ex) {
        System.out.println("error: "+ex);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mas = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ccheque = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tcheque = new javax.swing.JTable();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar.png"))); // NOI18N
        mas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masMouseClicked(evt);
            }
        });
        getContentPane().add(mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 70, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar_cancelar.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 70, 60));

        ccheque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nombre" }));
        ccheque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cchequeMouseClicked(evt);
            }
        });
        getContentPane().add(ccheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 260, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 204, 0));
        jLabel1.setText("Cobrar cheques  ");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 400, 40));

        tcheque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tcheque);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 600, 310));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void masMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masMouseClicked

            int i = Integer.parseInt(ccheque.getSelectedItem().toString());
            cobrar(i);
            combo();
            vercheque();
            //this.dispose();
        

        // TODO add your handling code here:
    }//GEN-LAST:event_masMouseClicked

    private void cchequeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cchequeMouseClicked
    combo();  
    vercheque();// TODO add your handling code here:
    }//GEN-LAST:event_cchequeMouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
combo();   
vercheque();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered
 public void cobrar(int mont ){
        try{

            cn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE",nb,cont);
            s=cn.createStatement();
            rs=s.executeQuery(" begin "
                             + " administrador.cobrar_cheque("+mont+");"
                             + "end; ");
             DesktopNotify.showDesktopMessage("Mensaje de Éxito", "Se ha retirado exitosamente.", DesktopNotify.SUCCESS);
          cn.close();
          
        }
        catch(Exception ex)
        {
            DesktopNotify.showDesktopMessage("Mensaje de Fallo", "No se pudo cobrar -- -- -- ."+ex.getMessage()+".", DesktopNotify.FAIL);
                     }
    }
 
 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ccheque;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mas;
    private javax.swing.JTable tcheque;
    // End of variables declaration//GEN-END:variables
}
