/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basededatos2;

import static basededatos2.elim_usuario.cn;
import ds.desktop.notify.DesktopNotify;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author hance
 */
public class validacion extends javax.swing.JFrame {
static Connection cn;
 static Statement s;
 static ResultSet rs;
 
 String nb=Pantallap.usuariodb;
 String cont=Pantallap.cnusuariobd;
    /**
     * Creates new form validacion
     */
    public validacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargar_imagen1();
        jmonto.setVisible(false);
        tmonto.setVisible(false);
        mas.setVisible(false);
        jnombre.setVisible(false);
        tnombre.setVisible(false);
        comnom();
    }
 public void cargar_imagen1 (){
       ImageIcon imagen = new ImageIcon ("C://Users//hance//Documents//IMAGENES PROYECTOS//fondo1.jpg");
        Icon icono = new ImageIcon (imagen.getImage().getScaledInstance(fondo.getWidth(), fondo.getHeight(), Image.SCALE_DEFAULT));
        fondo.setIcon(icono);
        this.repaint();
       }
 public void comnom()
    {
        try{
            cn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE",nb,cont);
            s=cn.createStatement();
            rs=s.executeQuery("select nombre from control_sistema where estado = 'activo'");
            cnombre.removeAllItems();
            while(rs.next()){
            cnombre.addItem(rs.getString(1));
            }
            cn.close();
        }
        catch(Exception ex)
        {
            System.out.println(ex.getMessage());
            
        }
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tnombre = new javax.swing.JTextField();
        jnombre = new javax.swing.JLabel();
        jmonto = new javax.swing.JLabel();
        tmonto = new javax.swing.JTextField();
        jcval = new javax.swing.JCheckBox();
        mas = new javax.swing.JLabel();
        menos = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cnombre = new javax.swing.JComboBox<>();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(tnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 140, 33));

        jnombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jnombre.setForeground(new java.awt.Color(102, 204, 0));
        jnombre.setText("NOMBRE");
        getContentPane().add(jnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 92, 33));

        jmonto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmonto.setForeground(new java.awt.Color(102, 204, 0));
        jmonto.setText("MONTO");
        getContentPane().add(jmonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 64, 34));
        getContentPane().add(tmonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 140, 30));

        jcval.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jcval.setForeground(new java.awt.Color(102, 204, 0));
        jcval.setText("Nueva Validacion");
        jcval.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcvalMouseClicked(evt);
            }
        });
        getContentPane().add(jcval, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 180, -1));

        mas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas.png"))); // NOI18N
        mas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masMouseClicked(evt);
            }
        });
        getContentPane().add(mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 50, 40));

        menos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menos.png"))); // NOI18N
        menos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menosMouseClicked(evt);
            }
        });
        getContentPane().add(menos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar_cancelar.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 70, 60));

        cnombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nombre" }));
        cnombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cnombreMouseClicked(evt);
            }
        });
        getContentPane().add(cnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 180, -1));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 593, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jcvalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcvalMouseClicked
if(jcval.isSelected()){
jmonto.setVisible(true);
tmonto.setVisible(true);
mas.setVisible(true);
menos.setVisible(false);
cnombre.setVisible(false);
jnombre.setVisible(true);
tnombre.setVisible(true);
}else {
jmonto.setVisible(false);
tmonto.setVisible(false);
mas.setVisible(false);
menos.setVisible(true);
cnombre.setVisible(true);
jnombre.setVisible(false);
tnombre.setVisible(false);
}    // TODO add your handling code here:
    }//GEN-LAST:event_jcvalMouseClicked

    private void masMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masMouseClicked

        try {
            String n = tnombre.getText();
            int mo= Integer.parseInt(tmonto.getText());
            crear(n,mo);
            this.dispose();
        } catch (Exception e) {
             DesktopNotify.showDesktopMessage("Mensaje de Fallo", "No se permiten Caracteres en el campo de Monto "+e.getMessage()+".", DesktopNotify.FAIL);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_masMouseClicked

    private void menosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosMouseClicked
       String nombres =cnombre.getSelectedItem().toString();
       eliminarcont(nombres);
       this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_menosMouseClicked

    private void cnombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnombreMouseClicked
    comnom();        // TODO add your handling code here:
    }//GEN-LAST:event_cnombreMouseClicked
 public void crear(String nom,int mont ){
        try{

            cn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE",nb,cont);
            s=cn.createStatement();
            rs=s.executeQuery("begin "
                             + "crear_nuevocontrol ('"+nom+"',"+mont+");"
                             + "end;");
             DesktopNotify.showDesktopMessage("Mensaje de Éxito", "Usuario "+nom+" ha sido creado.", DesktopNotify.SUCCESS);
          cn.close();
          
        }
        catch(Exception ex)
        {
            DesktopNotify.showDesktopMessage("Mensaje de Fallo", "No se pudo crear la Nueva validacion."+ex.getMessage()+".", DesktopNotify.FAIL);
                     }
    }
 
 public void eliminarcont(String nom ){
        try{
            cn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE",nb,cont);
            s=cn.createStatement();
            rs=s.executeQuery("begin "
                            + "eliminar_controlsistema ('"+nom+"');"
                             +" end;");
          cn.commit();
          rs.close();
          cn.close();
          DesktopNotify.showDesktopMessage("Mensaje de Éxito", " Usuario "+nom+" ha sido eliminado.", DesktopNotify.SUCCESS); 
        }
        catch(Exception ex)
        {
            DesktopNotify.showDesktopMessage("Mensaje de Fallo", "No se pudo crear la Nueva validacion."+ex.getMessage()+".", DesktopNotify.FAIL);
                     }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(validacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(validacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(validacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(validacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new validacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cnombre;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JCheckBox jcval;
    private javax.swing.JLabel jmonto;
    private javax.swing.JLabel jnombre;
    private javax.swing.JLabel mas;
    private javax.swing.JLabel menos;
    private javax.swing.JTextField tmonto;
    private javax.swing.JTextField tnombre;
    // End of variables declaration//GEN-END:variables
}
